// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBiaAHY10Oz-fN2afrPRgJ47Y4eIj5BbM',
    appId: '1:727728097114:web:69c7ef87bee53d3d185563',
    messagingSenderId: '727728097114',
    projectId: 'flutter-demo-630d5',
    authDomain: 'flutter-demo-630d5.firebaseapp.com',
    storageBucket: 'flutter-demo-630d5.appspot.com',
    measurementId: 'G-YTR84M51M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClTEdYugry_E51lMUg3qZQLSNtLthmavw',
    appId: '1:727728097114:android:a50caeb61e148d4b185563',
    messagingSenderId: '727728097114',
    projectId: 'flutter-demo-630d5',
    storageBucket: 'flutter-demo-630d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYQZSXyY3uUfl36T5auYl46MMlfH22WVM',
    appId: '1:727728097114:ios:9276008ff68245e8185563',
    messagingSenderId: '727728097114',
    projectId: 'flutter-demo-630d5',
    storageBucket: 'flutter-demo-630d5.appspot.com',
    iosBundleId: 'com.example.khoaLuanTotNghiep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYQZSXyY3uUfl36T5auYl46MMlfH22WVM',
    appId: '1:727728097114:ios:9276008ff68245e8185563',
    messagingSenderId: '727728097114',
    projectId: 'flutter-demo-630d5',
    storageBucket: 'flutter-demo-630d5.appspot.com',
    iosBundleId: 'com.example.khoaLuanTotNghiep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBiaAHY10Oz-fN2afrPRgJ47Y4eIj5BbM',
    appId: '1:727728097114:web:78e5140d3c7bab36185563',
    messagingSenderId: '727728097114',
    projectId: 'flutter-demo-630d5',
    authDomain: 'flutter-demo-630d5.firebaseapp.com',
    storageBucket: 'flutter-demo-630d5.appspot.com',
    measurementId: 'G-VR17RGX8FS',
  );
}
